name: Run default tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          vcpkg install openssl:x64-windows
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Run fmt check
        run: cargo fmt --check --verbose
      - name: Run tests
        run: cargo test --verbose

      - name: Build libiconv
        run: cargo build --no-default-features --features libiconv --verbose
      - name: Run clippy for libiconv
        run: cargo clippy --no-default-features --features libiconv --verbose
      - name: Run tests for libiconv
        run: cargo test --no-default-features --features libiconv --verbose

  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Run tests
        run: wasm-pack test --node
